# Script Gerado pelo FL Classificador Sequencial
# Execute este script no PowerShell para aplicar os nomes definitivamente.

Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2801.MP4" -NewName "001_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2802.MP4" -NewName "002_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2803.MP4" -NewName "003_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2804.MP4" -NewName "004_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2805.MP4" -NewName "005_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2806.MP4" -NewName "006_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2807.MP4" -NewName "007_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2808.MP4" -NewName "008_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2809.MP4" -NewName "009_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2810.MP4" -NewName "010_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2811.MP4" -NewName "011_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2812.MP4" -NewName "012_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2813.MP4" -NewName "013_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2814.MP4" -NewName "014_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2815.MP4" -NewName "015_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2816.MP4" -NewName "016_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2817.MP4" -NewName "017_0_filmagem_local_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2818.MP4" -NewName "018_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2819.MP4" -NewName "019_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2820.MP4" -NewName "020_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2821.MP4" -NewName "021_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2822.MP4" -NewName "022_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2823.MP4" -NewName "023_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2824.MP4" -NewName "024_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2825.MP4" -NewName "025_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2826.MP4" -NewName "026_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2827.MP4" -NewName "027_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2828.MP4" -NewName "028_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2829.MP4" -NewName "029_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2754.MP4" -NewName "030_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2830.MP4" -NewName "031_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2831.MP4" -NewName "032_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2755.MP4" -NewName "033_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2832.MP4" -NewName "034_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2756.MP4" -NewName "035_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2757.MP4" -NewName "036_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2833.MP4" -NewName "037_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2758.MP4" -NewName "038_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2834.MP4" -NewName "039_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2759.MP4" -NewName "040_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2835.MP4" -NewName "041_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2760.MP4" -NewName "042_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2761.MP4" -NewName "043_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2762.MP4" -NewName "044_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2763.MP4" -NewName "045_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2836.MP4" -NewName "046_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2837.MP4" -NewName "047_1_intimidade_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2764.MP4" -NewName "048_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2765.MP4" -NewName "049_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2766.MP4" -NewName "050_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2767.MP4" -NewName "051_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2768.MP4" -NewName "052_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2769.MP4" -NewName "053_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2770.MP4" -NewName "054_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2771.MP4" -NewName "055_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2772.MP4" -NewName "056_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2773.MP4" -NewName "057_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2774.MP4" -NewName "058_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2775.MP4" -NewName "059_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2776.MP4" -NewName "060_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2777.MP4" -NewName "061_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2838.MP4" -NewName "062_2_dominio_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2778.MP4" -NewName "063_1_intimidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2839.MP4" -NewName "064_2_dominio_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2840.MP4" -NewName "065_2_dominio_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2841.MP4" -NewName "066_2_dominio_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2842.MP4" -NewName "067_2_dominio_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2779.MP4" -NewName "068_nada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2843.MP4" -NewName "069_3_dominio_orientado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2780.MP4" -NewName "070_2_dominio_parado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2781.MP4" -NewName "071_2_dominio_parado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2844.MP4" -NewName "072_3_dominio_orientado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2782.MP4" -NewName "073_2_dominio_parado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2845.MP4" -NewName "074_3_dominio_orientado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2783.MP4" -NewName "075_2_dominio_parado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2846.MP4" -NewName "076_3_dominio_orientado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2784.MP4" -NewName "077_2_dominio_parado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2785.MP4" -NewName "078_3_dominio_orientado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2786.MP4" -NewName "079_3_dominio_orientado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2787.MP4" -NewName "080_3_dominio_orientado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2788.MP4" -NewName "081_3_dominio_orientado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2789.MP4" -NewName "082_3_dominio_orientado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2790.MP4" -NewName "083_nada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2791.MP4" -NewName "084_nada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2792.MP4" -NewName "085_3_dominio_orientado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2847.MP4" -NewName "086_4_saida_pressao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2848.MP4" -NewName "087_4_saida_pressao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2849.MP4" -NewName "088_4_saida_pressao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2850.MP4" -NewName "089_4_saida_pressao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2851.MP4" -NewName "090_4_saida_pressao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2852.MP4" -NewName "091_4_saida_pressao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2793.MP4" -NewName "092_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2794.MP4" -NewName "093_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2795.MP4" -NewName "094_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2796.MP4" -NewName "095_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2797.MP4" -NewName "096_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2798.MP4" -NewName "097_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2799.MP4" -NewName "098_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2800.MP4" -NewName "099_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2801.MP4" -NewName "100_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2802.MP4" -NewName "101_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2803.MP4" -NewName "102_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2804.MP4" -NewName "103_4_saida_pressao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2853.MP4" -NewName "104_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2854.MP4" -NewName "105_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2855.MP4" -NewName "106_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2856.MP4" -NewName "107_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2857.MP4" -NewName "108_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2858.MP4" -NewName "109_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2859.MP4" -NewName "110_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2860.MP4" -NewName "111_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2861.MP4" -NewName "112_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2862.MP4" -NewName "113_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2863.MP4" -NewName "114_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2864.MP4" -NewName "115_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2865.MP4" -NewName "116_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2866.MP4" -NewName "117_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2867.MP4" -NewName "118_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2868.MP4" -NewName "119_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2869.MP4" -NewName "120_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2870.MP4" -NewName "121_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2805.MP4" -NewName "122_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2806.MP4" -NewName "123_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2807.MP4" -NewName "124_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2871.MP4" -NewName "125_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2872.MP4" -NewName "126_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2808.MP4" -NewName "127_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2809.MP4" -NewName "128_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2873.MP4" -NewName "129_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2810.MP4" -NewName "130_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2874.MP4" -NewName "131_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2875.MP4" -NewName "132_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2811.MP4" -NewName "133_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2812.MP4" -NewName "134_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2813.MP4" -NewName "135_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2814.MP4" -NewName "136_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2815.MP4" -NewName "137_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2816.MP4" -NewName "138_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2876.MP4" -NewName "139_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2877.MP4" -NewName "140_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2878.MP4" -NewName "141_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2817.MP4" -NewName "142_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2879.MP4" -NewName "143_5_dominio_maq_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2818.MP4" -NewName "144_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2819.MP4" -NewName "145_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2820.MP4" -NewName "146_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2821.MP4" -NewName "147_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2822.MP4" -NewName "148_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2823.MP4" -NewName "149_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2880.MP4" -NewName "150_6_dominio_alto_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2824.MP4" -NewName "151_5_dominio_maq_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2881.MP4" -NewName "152_6_dominio_alto_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2825.MP4" -NewName "153_6_dominio_alto_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2826.MP4" -NewName "154_6_dominio_alto_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2882.MP4" -NewName "155_7_dr_luis_diaz_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2883.MP4" -NewName "156_7_dr_luis_diaz_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2884.MP4" -NewName "157_7_dr_luis_diaz_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2885.MP4" -NewName "158_7_dr_luis_diaz_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2886.MP4" -NewName "159_nada_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2887.MP4" -NewName "160_8_dr_R9_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2888.MP4" -NewName "161_8_dr_R9_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2889.MP4" -NewName "162_9_dr_giro_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2827.MP4" -NewName "163_7_dr_luis_diaz_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2890.MP4" -NewName "164_9_dr_giro_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2828.MP4" -NewName "165_7_dr_luis_diaz_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2891.MP4" -NewName "166_9_dr_giro_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2829.MP4" -NewName "167_8_dr_R9_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2830.MP4" -NewName "168_8_dr_R9_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2831.MP4" -NewName "169_9_dr_giro_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2832.MP4" -NewName "170_9_dr_giro_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2892.MP4" -NewName "171_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2893.MP4" -NewName "172_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2894.MP4" -NewName "173_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2833.MP4" -NewName "174_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2834.MP4" -NewName "175_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2895.MP4" -NewName "176_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2835.MP4" -NewName "177_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2896.MP4" -NewName "178_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2836.MP4" -NewName "179_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2837.MP4" -NewName "180_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2897.MP4" -NewName "181_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2838.MP4" -NewName "182_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2898.MP4" -NewName "183_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2839.MP4" -NewName "184_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2899.MP4" -NewName "185_10_atletismo_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2840.MP4" -NewName "186_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2841.MP4" -NewName "187_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2842.MP4" -NewName "188_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2843.MP4" -NewName "189_10_atletismo_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2844.MP4" -NewName "190_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2845.MP4" -NewName "191_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2846.MP4" -NewName "192_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2847.MP4" -NewName "193_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2848.MP4" -NewName "194_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2849.MP4" -NewName "195_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2850.MP4" -NewName "196_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2851.MP4" -NewName "197_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2852.MP4" -NewName "198_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2853.MP4" -NewName "199_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2854.MP4" -NewName "200_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2855.MP4" -NewName "201_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2856.MP4" -NewName "202_11_mobilidade_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2857.MP4" -NewName "203_12_entrevista_henrique_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2858.MP4" -NewName "204_12_entrevista_henrique_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2859.MP4" -NewName "205_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2860.MP4" -NewName "206_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2861.MP4" -NewName "207_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2862.MP4" -NewName "208_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2863.MP4" -NewName "209_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2864.MP4" -NewName "210_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2865.MP4" -NewName "211_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2866.MP4" -NewName "212_13_entrevista_felipe_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2867.MP4" -NewName "213_14_entrevista_otavio_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2868.MP4" -NewName "214_15_entrevista_luis_henrique_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2900.MP4" -NewName "215_16_dr_penteada_ronaldinho_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2901.MP4" -NewName "216_17_dr_penteada_dupla_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2902.MP4" -NewName "217_18_dr_360_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2903.MP4" -NewName "218_19_dr_retorno_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2904.MP4" -NewName "219_20_dr_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2905.MP4" -NewName "220_20_dr_parado_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2869.MP4" -NewName "221_16_dr_pedalada_ronaldinho_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2870.MP4" -NewName "222_17_dr_penteada_dupla_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2906.MP4" -NewName "223_21_dr_corte_interno_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2871.MP4" -NewName "224_18_dr_360_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2907.MP4" -NewName "225_22_dr_puxada_neymar_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2872.MP4" -NewName "226_19_dr_retorno_coutinho_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2908.MP4" -NewName "227_23_dr_messi_croqueta_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2873.MP4" -NewName "228_20_dr_parado_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2874.MP4" -NewName "229_20_dr_parado_doue_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2909.MP4" -NewName "230_24_dr_denilson_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2875.MP4" -NewName "231_21_dr_corte_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2910.MP4" -NewName "232_25_dr_elastico_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2876.MP4" -NewName "233_22_dr_puxada_neymar_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2877.MP4" -NewName "234_23_dr_messi_croqueta_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2878.MP4" -NewName "235_24_dr_denilson_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2879.MP4" -NewName "236_25_dr_romario_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2911.MP4" -NewName "237_30_fatiada_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2912.MP4" -NewName "238_31_chapa_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2880.MP4" -NewName "239_30_fatiada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2913.MP4" -NewName "240_31_chapa_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2881.MP4" -NewName "241_nada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2882.MP4" -NewName "242_nada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2914.MP4" -NewName "243_32_peito_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2915.MP4" -NewName "244_32_peito_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2883.MP4" -NewName "245_33_top_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2916.MP4" -NewName "246_34_chapa_efeito_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2884.MP4" -NewName "247_31_chapa_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2885.MP4" -NewName "248_32_peito_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2917.MP4" -NewName "249_35_3_dedos_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2886.MP4" -NewName "250_34_chapa_efeito_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2918.MP4" -NewName "251_40_marcacao_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2887.MP4" -NewName "252_35_3_dedos_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2919.MP4" -NewName "253_41_primeira_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2888.MP4" -NewName "254_nada_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2920.MP4" -NewName "255_nada_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2889.MP4" -NewName "256_40_marcacao_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 1\PRIVATE\M4ROOT\CLIP\GUI2921.MP4" -NewName "257_41_primeira_cartao1.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2890.MP4" -NewName "258_41_primeira_cartao2.MP4" -ErrorAction SilentlyContinue
Rename-Item -Path "E:\DATA\FL Filmagem - Gemini\cartao 2\PRIVATE\M4ROOT\CLIP\C2891.MP4" -NewName "259_41_primeira_cartao2.MP4" -ErrorAction SilentlyContinue
